### ISSUE TITLE
URLs in installer are blocked by firewall

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/windows-installer#20]
I just got an e-mail from the IT staff at the Federal Reserve Board.  Apparently their firewall blocks the files the installer uses to setup nano, etc...

I told them we can manually configure the editor at the start of the git tutorial by doing something like:
`$ git config --global core.editor notepad`

Would moving the installer zip into this repo be a solution?

This is the e-mail I got

> I am one of the IT staff for the Board, IF Division, and I’m assisting with the setup of our laptops for next week’s class.  My manager, Jim Dahl, attempted to install SWC installer as a test in a laptop and he ran into problems, as described below:
>  
> “ It attempts to go out to the Internet to download some stuff (some Python packages?) which gets blocked by our firewalls. You can see that happen if you run it from a command prompt. The initial installer just creates some new installation stuff in c:\program files (x86)\swc-installer, and then prompts you to run it. If you let it run it, you can’t see the results because the window disappears. But, you can go to that directory in a command prompt and run the swc-windows-installer from the prompt, then you can see the error where it tries to open a URL:
> C:\Program Files (x86)\swc-installer>swc-windows-installer
> Preparing your Software Carpentry awesomeness!
> installer version 0.1
> create nosetests entrypoint C:\Users\m1jad01\.swc\bin\nosetests
> Traceback (most recent call last):
>   File "swc-windows-installer.py", line 299, in <module>
>   File "swc-windows-installer.py", line 266, in main
>   File "swc-windows-installer.py", line 149, in install_nano
>   File "swc-windows-installer.py", line 134, in zip_install
>   File "swc-windows-installer.py", line 67, in download
>   File "urllib2.pyc", line 127, in urlopen
>   File "urllib2.pyc", line 404, in open
>   File "urllib2.pyc", line 422, in _open
>   File "urllib2.pyc", line 382, in _call_chain
>   File "urllib2.pyc", line 1214, in http_open
>   File "urllib2.pyc", line 1184, in do_open
> urllib2.URLError: <urlopen error [Errno 10060] A connection attempt failed becau
> se the connected party did not properly respond after a period of time, or estab
> lished connection failed because connected host has failed to respond>
>  
> C:\Program Files (x86)\swc-installer>”

**Comment by gvwilson** [comment]
Status?

**Comment by wking** [comment]
On Sun, Mar 15, 2015 at 04:26:04PM -0700, Greg Wilson wrote:
> Status?

@chendaniely went quiet, so we stopped moving forward ;).  I'm still
open to a configurable mirror IP address.  Still, I'm not sure how
that would work with an Inno-Setup-compiled installer (maybe use an
environment variable to pass in the altered IP?).  And folks should be
running their install before the workshop, so the instructor won't be
there to mirror the sources.  I suppose they'd have global network
access whenever they try to install (otherwise how to they get the
installer script/executable?), so maybe we only need to handle the
“instructor is in the room running a local mirror” case to unstick
folks who couldn't manage to run the setup script/executable
beforehand.  Anyhow, all this is complicated/hazy enough that I'm fine
waiting until we actually need it before coding it up.

**Comment by chendaniely** [comment]
The Federal Reserve Board was an unique case since they provided all the students with laptops.  I personally have not been to any other workshop where this was an issue, so it doesn't seem like a pressing issue.

**Comment by ethanwhite** [comment]
I'm +1 for closing this.

**Comment by wking** [comment]
Closed unless/until it comes up again.
